# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00fe48cda22c10aa497298f1d289dd6246ca6b202c0adf791a3a71f6fd134bcd2db43d99e966385d6845aa609e3f80c900c7abdab335f0430b0bc56be9470216

test:
  secret_key_base: d30357a6fd6d3d6d77eb205ef7d53f56e605bf4f0269c710458a5cbc0408d64f2d49812be7c5fe2c4deb9d65599b5a12097f801cf0d52fd917073672aa615b6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
